### ISSUE TITLE
Where is the source , only compiled code here ?

### ISSUE THREAD

**Issue by Tsoccerguy3** [jtrent238/Minecraft-Skin-Viewer#1]
I'll reserve judgement , of what your up to , for later ?

**Comment by jtrent238** [comment]
This file contains all the source code: [Minecraft Skin Viewer.xojo_binary_project](https://github.com/jtrent238/Minecraft-Skin-Viewer/blob/master/Minecraft%20Skin%20Viewer.xojo_binary_project), and you need [XOJO](http://www.xojo.com/) to open the file.

![](http://puu.sh/tRx2k/ce5e91520c.png)


For more info on XOJO project files [click here](http://developer.xojo.com/userguide/project-types).
